[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom.variants.design]
capital-g = "toothed-serifless-hookless"
capital-q = "straight"
i = "hooky"
l = "serifed-flat-tailed"
t = "standard-short-neck"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
lower-mu = "tailless"
zero = "dotted"
two = "straight-neck"
three = "flat-top"
asterisk = "penta-low"
brace = "straight"
ampersand = "upper-open"
dollar = "open"
cent = "open"
percent = "dots"
lig-ltgteq = "slanted"

[buildPlans.iosevka-custom.ligations]
inherits = "dlig"

