[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
        \ 'colorscheme' : 'nord',
        \ 'active' : {
        \   'left' : [ [ 'mode' ],
        \              [ 'gitbranch', 'filename', 'readonly', 'modified' ] ]
        \ },
        \ 'component_function' : {
        \   'gitbranch' : 'fugitive#head'
        \ },
        \ }
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_char = '·'
    let g:indentLine_leadingSpaceChar = '·'
    let g:indentLine_leadingSpaceEnabled = 1
    let g:indentLine_concealcursor = ''
'''

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
    let g:better_whitespace_enabled = 1
    let g:better_whitespace_filetypes_blacklist=['diff', 'help', 'markdown']
    let g:strip_whitespace_on_save = 1
    let g:strip_whitespace_confirm = 0
    let g:better_whitespace_guicolor = '#bf616a'
'''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-line'

[[plugins]]
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
    let g:nord_italics = 1
    let g:nord_underline = 1
    let g:nord_uniform_diff_background = 1
    let g:nord_cursor_line_number_background = 1
    colorscheme nord
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'junegunn/goyo.vim'
hook_add = '''
    let g:goyo_width = 100
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
build = 'yarn install --frozen-lockfile'

