[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell', 'hs', 'lhs']
hook_add = '''
    let g:haskell_enable_quantification = 1
    let g:haskell_enable_recursivedo = 1
    let g:haskell_arrowsyntax = 1
    let g:haskell_enable_pattern_synonyms = 1
    let g:haskell_indent_disable = 1
'''

[[plugins]]
repo = 'purescript-contrib/purescript-vim'
on_ft = ['purescript', 'purs']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescriptreact']

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascriptreact', 'typescriptreact']

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xml', 'javascriptreact', 'typescriptreact']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescriptreact']
hook_add = '''
    let g:typescript_indent_disable = 1
'''

[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'
on_ft = [
    'javascript',
    'typescript',
    'css',
    'less',
    'scss',
    'jsom',
    'graphql',
    'markdown',
    'vue',
    'lua',
    'php',
    'python',
    'ruby',
    'html',
    'swift',
]

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
